hotel_facility_mapping = {
			'bowling': '1',
			'spa': '2',
			'heated outdoor pool': '3',
			'skidoo': '4',
			'walking': '5',
			'gym': '6',
			'parapenting': '7',
			'snowshoeing': '8',
			'snow sure': '9',
			'high altitude skiing': '10',
			'high-altitude skiing': '10',
			'village resort': '11',
			'family friendly': '12',
			'tv': '13',
			'television': '13',
			'sauna': '14',
			'balcony': '15',
			'outdoor pool': '16',
			'outdoor pools': '16',
			'swimming pool': '17',
			'swimming pools': '17',
			'restaurant': '18',
			'bar': '19',
			'dishwasher': '20',
			'coffee': '21',
			'oven': '22',
			'fridge': '23',
			'refrigerator': '24',
			'microwave': '25'
		}
